#!/bin/sh

REGISTRY="${DOCKER_LOCAL_REGISTRY}"
IMAGE="node:10"
FULL="${REGISTRY}${IMAGE}"

if [ -z "${PORT}" ]; then
	PORTENV=""
else
	PORTENV="-e PORT=${PORT}"
fi

if [ -z "${INSIDEPORT}" ]; then
	INSIDEPORT="${PORT}"
else
	PORTENV="-e PORT=${INSIDEPORT}"
fi

if [ -z "${PORT}" ] ; then
	PORTSTR=
else
	PORTSTR="-p ${PORT}:${INSIDEPORT}"
fi

WORKDIR="/app"
docker run \
	--user "node" \
	-it \
	${PORTSTR} \
	${PORTENV} \
	--rm \
	-w "${WORKDIR}" \
	-v "$(pwd):${WORKDIR}" \
	"${FULL}" "$@"
